---
name: CI Pipeline

on:  # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:

jobs:
  check_style:
    runs-on: ubuntu-latest
    container: docker.io/akospasztor/docker-python:3.12-linux-2.0.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install package
        run: pip install -e ".[test]"
      - name: Run editorconfig-checker
        run: ec --exclude "^(\.git|.*egg-info.*)$"
      - name: Run flake8
        run: flake8
      - name: Run yamllint
        run: yamllint --strict .
  run_tests:
    runs-on: ubuntu-latest
    container: docker.io/akospasztor/docker-python:3.12-linux-2.0.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install package
        run: pip install -e ".[test]"
      - name: Run pytest
        run: >
          pytest -ra
          --junit-xml=tests/build/report.xml
          --html=tests/build/report.html
          --self-contained-html
      - name: Upload test report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: tests/build
